"""Family-scoped commitment actions exposed to the agent."""

from __future__ import annotations
from datetime import datetime
from typing import Optional
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.commitment import Commitment
from typing import Any


# Service calls own duplicate detection, family checks, and valid status transitions.
async def create_commitment(
    *,
    service: Any,
    family_id: str,
    title: str,
    commitment_type: str,
    due_date: str | None = None,
    amount: float | None = None,
    member_id: str | None = None,
    description: str | None = None,
    source: str = "agent",
) -> Any:
    """Create a commitment while letting the service enforce duplicate rules."""
    # All user-entered details arrive validated against CreateCommitmentInput first.
    # Preserve the validated source label for audit and provenance.
    return await service.create_commitment(
        family_id=family_id,
        title=title,
        commitment_type=commitment_type,
        due_date=due_date,
        amount=amount,
        member_id=member_id,
        description=description,
        source=source,
    )


async def search_commitments(
    *,
    service: Any,
    family_id: str,
    query: str | None = None,
    status: str | None = None,
    due_before: str | None = None,
    due_after: str | None = None,
    member_id: str | None = None,
    limit: int = 20,
) -> Any:
    """Search commitments within the current family's records."""
    # The family ID is always injected by the application, never generated by the model.
    # Pass filters individually instead of allowing the model to construct a database query.
    return await service.search_commitments(
        family_id=family_id,
        query=query,
        status=status,
        due_before=due_before,
        due_after=due_after,
        member_id=member_id,
        limit=limit,
    )


async def update_commitment(
    *,
    service: Any,
    family_id: str,
    commitment_id: str,
    title: str | None = None,
    due_date: str | None = None,
    status: str | None = None,
    amount: float | None = None,
    member_id: str | None = None,
    description: str | None = None,
) -> Any:
    """Update the allowlisted commitment fields via the transition-aware service."""
    # Build an allowlisted update object; extra LLM fields cannot reach this handler.
    # None values mean "not supplied" here, so they do not erase existing information.
    changes = {
        key: value
        for key, value in {
            "title": title,
            "due_date": due_date,
            "status": status,
            "amount": amount,
            "member_id": member_id,
            "description": description,
        }.items()
        if value is not None
    }
    # Empty updates are usually an unhelpful model call, so ask the caller to provide a change.
    if not changes:
        raise ValueError("At least one commitment field must be provided")
    # Delegate authorization, lookup, and transition checks to the business service.
    return await service.update_commitment(
        family_id=family_id,
        commitment_id=commitment_id,
        changes=changes,
    )
